name: Release stable
on:
  push:
    branches:
      - main
      - next

permissions: write-all

jobs:
  unit_tests:
    name: Unit tests
    uses: ./.github/workflows/unit_tests.yml
  
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup (cache, dependencies)
        uses: ./.github/actions/install_and_cache_dependencies

      - name: Build
        run: pnpm build

      - name: Create release (or Pull Request)
        uses: changesets/action@v1
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: pnpm release
      # - name: Release
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     GITHUB_TOKEN: ${{ secrets.TELLUS_ACCESS_TOKEN }}
      #   run: pnpm semantic-release
