name: Release stable
on:
  push:
    branches:
      - main
      - next

permissions: write-all

jobs:
  deps:
    name: Dependencies
    uses: ./.github/workflows/dependencies.yml

  unit_tests:
    name: Unit tests
    needs: deps
    uses: ./.github/workflows/unit_tests.yml
  
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js

        uses: actions/setup-node@v3.8.1
        with:
          node-version: "19"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          run_install: false

      - name: Detect PNPM store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
      # - name: Release
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     GITHUB_TOKEN: ${{ secrets.TELLUS_ACCESS_TOKEN }}
      #   run: pnpm semantic-release
