name: Unit Tests
on:
  workflow_call:
    inputs:
      unused:
        type: boolean
        description: Unused, but you must define something to use workflow_call.

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19"
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          run_install: true
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test